### ISSUE TITLE
migration command

### ISSUE THREAD

**Issue by patrick-fls** [flagshipcompany/silex-helpers#1]
Simple migration command with symfony's command line (see silex skelton for example) and doctrine's silex DBAL.
- [x] The command should be call `migrate`
- [x] One of 2 arguments are required `up` or `down`
- [x] Parameters should support optional `--env`, `--db`, `--path`
- [x] The db path is by default gotten from `$app['migrations.path'];` 

Similar to Laravel, 
- [x] migrations are stored in to a `migrations` table on the target db. table should be created if doesn't exist
- [x] 3 columns are required: `name` of the file, `md5` of the file, and the `batch`
- [x] A migration file is expected to be a class with simply the `up()` and a `down()` function. Create a interface for programmers to use when writing a migration.
- [x] Both functions return _raw SQL only_
- [x] The command simply executes the raw SQL returned by the `up()` or `down()` functions in _a transaction_
- [x] Each new file (different md5) not present in the `migration` table is part of the same `batch` number and is incremented by `+1`when migrating `up`
-  [x] migrating `down` runs all the `down()` statements from the LAST `batch` number and removes those rows from the db.
-  [x] add scaffolding
  That's it! very simple!

**Comment by yi-FLS** [comment]
// How-to use command
use Flagship\Components\Helpers\Database\Migrations\Commands\MigrateCommand;
use Flagship\Components\Helpers\Database\Migrations\Commands\MigrateMakeCommand;
// include $app;

$cli = new \Symfony\Component\Console\Application('dev' /\* dev|prod|staging*/);
$cli->add(new MigrateCommand($app));
$cli->add(new MigrateMakeCommand($app));
$cli->run();

**Comment by yi-FLS** [comment]
please put db.options as a subkey - value pair within the environment :
eg: $app['prod']['db.options'] = [..];
